version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/build/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
  ValidateService:
    - location: scripts/validate_server
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
